export const trendingData = {
	hentai_videos: [
		{
			id: 3151,
			name: "Majo wa Kekkyoku Sono Kyaku to 2",
			slug: "majo-wa-kekkyoku-sono-kyaku-to-2",
			created_at: "2023-11-15T20:48:18.494Z",
			released_at: "2023-10-26T15:52:31.000Z",
			views: 2291423,
			interests: 77618,
			poster_url:
				"https://akidoo.top/images/posters/majo-wa-kekkyoku-sono-kyaku-to-2-pv1.png",
			cover_url:
				"https://akidoo.top/images/covers/majo-wa-kekkyoku-sono-kyaku-to-2-cv1.png",
			is_hard_subtitled: true,
			brand: "Pink Pineapple",
			duration_in_ms: 0,
			is_censored: true,
			rating: 0,
			likes: 9568,
			dislikes: 130,
			downloads: 78919,
			monthly_rank: 1,
			brand_id: "67",
			is_banned_in: "JP",
			preview_url: null,
			primary_color: null,
			created_at_unix: 1700081298,
			released_at_unix: 1698335551,
		},
		{
			id: 3156,
			name: "Sweet and Hot 1",
			slug: "sweet-and-hot-1",
			created_at: "2023-11-28T02:05:29.525Z",
			released_at: "2023-11-10T15:52:36.000Z",
			views: 1563247,
			interests: 51948,
			poster_url: "https://akidoo.top/images/posters/sweet-and-hot-1-pv1.png",
			cover_url: "https://akidoo.top/images/covers/sweet-and-hot-1-cv1.png",
			is_hard_subtitled: true,
			brand: "Queen Bee",
			duration_in_ms: 0,
			is_censored: true,
			rating: 0,
			likes: 7879,
			dislikes: 156,
			downloads: 49377,
			monthly_rank: 2,
			brand_id: "72",
			is_banned_in: "JP",
			preview_url: null,
			primary_color: null,
			created_at_unix: 1701137129,
			released_at_unix: 1699631556,
		},
		{
			id: 3149,
			name: "Mahou Touki Lilustear 1",
			slug: "mahou-touki-lilustear-1",
			created_at: "2023-11-13T20:39:51.653Z",
			released_at: "2023-10-26T15:52:29.000Z",
			views: 1282877,
			interests: 54562,
			poster_url:
				"https://akidoo.top/images/posters/mahou-touki-lilustear-1-pv1.png",
			cover_url:
				"https://akidoo.top/images/covers/mahou-touki-lilustear-1-cv1.png",
			is_hard_subtitled: true,
			brand: "Magin Label",
			duration_in_ms: 0,
			is_censored: true,
			rating: 0,
			likes: 3809,
			dislikes: 473,
			downloads: 29599,
			monthly_rank: 3,
			brand_id: "54",
			is_banned_in: "JP",
			preview_url: null,
			primary_color: null,
			created_at_unix: 1699907991,
			released_at_unix: 1698335549,
		},
		{
			id: 3147,
			name: "Kokuhaku...... 2",
			slug: "kokuhaku-2",
			created_at: "2023-10-31T15:39:11.387Z",
			released_at: "2023-09-28T15:52:27.000Z",
			views: 1571783,
			interests: 68228,
			poster_url: "https://akidoo.top/images/posters/kokuhaku-2-pv1.png",
			cover_url: "https://akidoo.top/images/covers/kokuhaku-2-cv1.png",
			is_hard_subtitled: true,
			brand: "nur",
			duration_in_ms: 0,
			is_censored: true,
			rating: 0,
			likes: 4614,
			dislikes: 175,
			downloads: 40591,
			monthly_rank: 4,
			brand_id: "131",
			is_banned_in: "JP",
			preview_url: null,
			primary_color: null,
			created_at_unix: 1698766751,
			released_at_unix: 1695916347,
		},
		{
			id: 3150,
			name: "Aoharu Snatch 2",
			slug: "aoharu-snatch-2",
			created_at: "2023-11-15T20:47:37.931Z",
			released_at: "2023-10-19T15:52:30.000Z",
			views: 1271080,
			interests: 59695,
			poster_url: "https://akidoo.top/images/posters/aoharu-snatch-2-pv1.png",
			cover_url: "https://akidoo.top/images/covers/aoharu-snatch-2-cv1.png",
			is_hard_subtitled: true,
			brand: "Queen Bee",
			duration_in_ms: 0,
			is_censored: true,
			rating: 0,
			likes: 3700,
			dislikes: 316,
			downloads: 42015,
			monthly_rank: 5,
			brand_id: "72",
			is_banned_in: "JP",
			preview_url: null,
			primary_color: null,
			created_at_unix: 1700081257,
			released_at_unix: 1697730750,
		},
		{
			id: 3141,
			name: "Tsuma ni Damatte Sokubaikai ni Ikun ja Nakatta 1",
			slug: "tsuma-ni-damatte-sokubaikai-ni-ikun-ja-nakatta-1",
			created_at: "2023-10-15T12:57:17.270Z",
			released_at: "2023-10-05T15:52:21.000Z",
			views: 4546536,
			interests: 113006,
			poster_url:
				"https://akidoo.top/images/posters/tsuma-ni-damatte-sokubaikai-ni-ikun-ja-nakatta-1-pv1.png",
			cover_url:
				"https://akidoo.top/images/covers/tsuma-ni-damatte-sokubaikai-ni-ikun-ja-nakatta-1-cv1.png",
			is_hard_subtitled: true,
			brand: "Antechinus",
			duration_in_ms: 0,
			is_censored: true,
			rating: 0,
			likes: 15442,
			dislikes: 352,
			downloads: 154174,
			monthly_rank: 6,
			brand_id: "141",
			is_banned_in: "JP",
			preview_url: null,
			primary_color: null,
			created_at_unix: 1697374637,
			released_at_unix: 1696521141,
		},
		{
			id: 3153,
			name: "Mihitsu no Koi 1",
			slug: "mihitsu-no-koi-1",
			created_at: "2023-11-21T22:27:02.674Z",
			released_at: "2023-10-26T15:52:33.000Z",
			views: 1139150,
			interests: 54229,
			poster_url: "https://akidoo.top/images/posters/mihitsu-no-koi-1-pv1.png",
			cover_url: "https://akidoo.top/images/covers/mihitsu-no-koi-1-cv1.png",
			is_hard_subtitled: true,
			brand: "nur",
			duration_in_ms: 0,
			is_censored: true,
			rating: 0,
			likes: 4934,
			dislikes: 126,
			downloads: 38962,
			monthly_rank: 7,
			brand_id: "131",
			is_banned_in: "JP",
			preview_url: null,
			primary_color: null,
			created_at_unix: 1700605622,
			released_at_unix: 1698335553,
		},
		{
			id: 3154,
			name: "Doukyo Suru Neneki 1",
			slug: "doukyo-suru-neneki-1",
			created_at: "2023-11-28T01:21:33.067Z",
			released_at: "2023-11-09T15:52:34.000Z",
			views: 1037084,
			interests: 42141,
			poster_url:
				"https://akidoo.top/images/posters/doukyo-suru-neneki-1-pv1.png",
			cover_url:
				"https://akidoo.top/images/covers/doukyo-suru-neneki-1-cv1.png",
			is_hard_subtitled: true,
			brand: "King Bee",
			duration_in_ms: 0,
			is_censored: true,
			rating: 0,
			likes: 6159,
			dislikes: 150,
			downloads: 36011,
			monthly_rank: 8,
			brand_id: "46",
			is_banned_in: "JP",
			preview_url: null,
			primary_color: null,
			created_at_unix: 1701134493,
			released_at_unix: 1699545154,
		},
		{
			id: 3148,
			name: "Sleepless Nocturne 2",
			slug: "sleepless-nocturne-2",
			created_at: "2023-10-31T15:59:45.506Z",
			released_at: "2023-10-26T15:52:28.000Z",
			views: 1346315,
			interests: 66093,
			poster_url:
				"https://akidoo.top/images/posters/sleepless-nocturne-2-pv1.png",
			cover_url:
				"https://akidoo.top/images/covers/sleepless-nocturne-2-cv1.png",
			is_hard_subtitled: true,
			brand: "Showten",
			duration_in_ms: 0,
			is_censored: true,
			rating: 0,
			likes: 4251,
			dislikes: 371,
			downloads: 35800,
			monthly_rank: 9,
			brand_id: "82",
			is_banned_in: "JP",
			preview_url: null,
			primary_color: null,
			created_at_unix: 1698767985,
			released_at_unix: 1698335548,
		},
		{
			id: 3155,
			name: "Kozukuri Ninkatsu Bu! 1",
			slug: "kozukuri-ninkatsu-bu-1",
			created_at: "2023-11-28T01:48:59.159Z",
			released_at: "2023-11-09T15:52:35.000Z",
			views: 837902,
			interests: 40450,
			poster_url:
				"https://akidoo.top/images/posters/kozukuri-ninkatsu-bu-1-pv1.png",
			cover_url:
				"https://akidoo.top/images/covers/kozukuri-ninkatsu-bu-1-cv1.png",
			is_hard_subtitled: true,
			brand: "Mary Jane",
			duration_in_ms: 0,
			is_censored: true,
			rating: 0,
			likes: 5889,
			dislikes: 85,
			downloads: 33600,
			monthly_rank: 10,
			brand_id: "56",
			is_banned_in: "JP",
			preview_url: null,
			primary_color: null,
			created_at_unix: 1701136139,
			released_at_unix: 1699545155,
		},
		{
			id: 3146,
			name: "Night Tail 1",
			slug: "night-tail-1",
			created_at: "2023-10-29T18:10:49.623Z",
			released_at: "2023-09-28T15:52:26.000Z",
			views: 1166451,
			interests: 60478,
			poster_url: "https://akidoo.top/images/posters/night-tail-1-pv1.png",
			cover_url: "https://akidoo.top/images/covers/night-tail-1-cv1.png",
			is_hard_subtitled: true,
			brand: "Magin Label",
			duration_in_ms: 0,
			is_censored: true,
			rating: 0,
			likes: 6235,
			dislikes: 191,
			downloads: 34895,
			monthly_rank: 11,
			brand_id: "54",
			is_banned_in: "JP",
			preview_url: null,
			primary_color: null,
			created_at_unix: 1698603049,
			released_at_unix: 1695916346,
		},
		{
			id: 3145,
			name: "Junjou Decamelon 2",
			slug: "junjou-decamelon-2",
			created_at: "2023-10-29T18:10:24.760Z",
			released_at: "2023-10-12T15:52:25.000Z",
			views: 1193872,
			interests: 62674,
			poster_url:
				"https://akidoo.top/images/posters/junjou-decamelon-2-pv1.png",
			cover_url: "https://akidoo.top/images/covers/junjou-decamelon-2-cv1.png",
			is_hard_subtitled: true,
			brand: "Queen Bee",
			duration_in_ms: 0,
			is_censored: true,
			rating: 0,
			likes: 5225,
			dislikes: 184,
			downloads: 42150,
			monthly_rank: 12,
			brand_id: "72",
			is_banned_in: "JP",
			preview_url: null,
			primary_color: null,
			created_at_unix: 1698603024,
			released_at_unix: 1697125945,
		},
		{
			id: 3142,
			name: "Tsuma ni Damatte Sokubaikai ni Ikun ja Nakatta 2",
			slug: "tsuma-ni-damatte-sokubaikai-ni-ikun-ja-nakatta-2",
			created_at: "2023-10-15T12:57:21.248Z",
			released_at: "2023-10-05T15:52:22.000Z",
			views: 3054409,
			interests: 93477,
			poster_url:
				"https://akidoo.top/images/posters/tsuma-ni-damatte-sokubaikai-ni-ikun-ja-nakatta-2-pv1.png",
			cover_url:
				"https://akidoo.top/images/covers/tsuma-ni-damatte-sokubaikai-ni-ikun-ja-nakatta-2-cv1.png",
			is_hard_subtitled: true,
			brand: "Antechinus",
			duration_in_ms: 0,
			is_censored: true,
			rating: 0,
			likes: 10168,
			dislikes: 258,
			downloads: 129071,
			monthly_rank: 13,
			brand_id: "141",
			is_banned_in: "JP",
			preview_url: null,
			primary_color: null,
			created_at_unix: 1697374641,
			released_at_unix: 1696521142,
		},
		{
			id: 3152,
			name: "Korashime 2: Kyouikuteki Depaga Shidou 4",
			slug: "korashime-2-kyouikuteki-depaga-shidou-4",
			created_at: "2023-11-21T22:26:55.735Z",
			released_at: "2023-10-26T15:52:32.000Z",
			views: 751745,
			interests: 46584,
			poster_url:
				"https://akidoo.top/images/posters/korashime-2-kyouikuteki-depaga-shidou-4-pv1.png",
			cover_url:
				"https://akidoo.top/images/covers/korashime-2-kyouikuteki-depaga-shidou-4-cv1.png",
			is_hard_subtitled: true,
			brand: "PoRO",
			duration_in_ms: 0,
			is_censored: true,
			rating: 0,
			likes: 3420,
			dislikes: 92,
			downloads: 25037,
			monthly_rank: 14,
			brand_id: "70",
			is_banned_in: "JP",
			preview_url: null,
			primary_color: null,
			created_at_unix: 1700605615,
			released_at_unix: 1698335552,
		},
		{
			id: 3143,
			name: "JK Ikinari Doukyo? Micchaku!? Hatsu Ecchi!!? 2",
			slug: "jk-ikinari-doukyo-micchaku-hatsu-ecchi-2",
			created_at: "2023-10-27T19:50:19.500Z",
			released_at: "2023-10-05T15:52:23.000Z",
			views: 1254683,
			interests: 67692,
			poster_url:
				"https://akidoo.top/images/posters/jk-ikinari-doukyo-micchaku-hatsu-ecchi-2-pv1.png",
			cover_url:
				"https://akidoo.top/images/covers/jk-ikinari-doukyo-micchaku-hatsu-ecchi-2-cv1.png",
			is_hard_subtitled: true,
			brand: "King Bee",
			duration_in_ms: 0,
			is_censored: true,
			rating: 0,
			likes: 6951,
			dislikes: 109,
			downloads: 46630,
			monthly_rank: 15,
			brand_id: "46",
			is_banned_in: "JP",
			preview_url: null,
			primary_color: null,
			created_at_unix: 1698436219,
			released_at_unix: 1696521143,
		},
		{
			id: 3157,
			name: "Tsuma Netori Kan: Bijutsu Kyoushi no Baai 1",
			slug: "tsuma-netori-kan-bijutsu-kyoushi-no-baai-1",
			created_at: "2023-11-30T17:18:00.653Z",
			released_at: "2023-11-28T15:52:37.000Z",
			views: 636266,
			interests: 31470,
			poster_url:
				"https://akidoo.top/images/posters/tsuma-netori-kan-bijutsu-kyoushi-no-baai-1-pv1.png",
			cover_url:
				"https://akidoo.top/images/covers/tsuma-netori-kan-bijutsu-kyoushi-no-baai-1-cv1.png",
			is_hard_subtitled: true,
			brand: "ZIZ",
			duration_in_ms: 0,
			is_censored: true,
			rating: 0,
			likes: 2396,
			dislikes: 354,
			downloads: 21949,
			monthly_rank: 16,
			brand_id: "106",
			is_banned_in: "JP",
			preview_url: null,
			primary_color: null,
			created_at_unix: 1701364680,
			released_at_unix: 1701186757,
		},
		{
			id: 3071,
			name: "Majo wa Kekkyoku Sono Kyaku to 1",
			slug: "majo-wa-kekkyoku-sono-kyaku-to-1",
			created_at: "2023-03-02T17:57:59.000Z",
			released_at: "2023-02-23T15:51:11.000Z",
			views: 5340417,
			interests: 170108,
			poster_url:
				"https://akidoo.top/images/posters/majo-wa-kekkyoku-sono-kyaku-to-1-pv1.png",
			cover_url:
				"https://akidoo.top/images/covers/majo-wa-kekkyoku-sono-kyaku-to-1-cv1.png",
			is_hard_subtitled: true,
			brand: "Pink Pineapple",
			duration_in_ms: 0,
			is_censored: true,
			rating: 0,
			likes: 11710,
			dislikes: 81,
			downloads: 213346,
			monthly_rank: 17,
			brand_id: "67",
			is_banned_in: "JP",
			preview_url: null,
			primary_color: null,
			created_at_unix: 1677779879,
			released_at_unix: 1677167471,
		},
		{
			id: 3136,
			name: "Kono Koi ni Kizuite 1",
			slug: "kono-koi-ni-kizuite-1",
			created_at: "2023-09-12T10:00:44.980Z",
			released_at: "2023-08-24T15:52:16.000Z",
			views: 6741032,
			interests: 163805,
			poster_url:
				"https://akidoo.top/images/posters/kono-koi-ni-kizuite-1-pv1.png",
			cover_url:
				"https://akidoo.top/images/covers/kono-koi-ni-kizuite-1-cv1.png",
			is_hard_subtitled: true,
			brand: "Pink Pineapple",
			duration_in_ms: 0,
			is_censored: true,
			rating: 0,
			likes: 27772,
			dislikes: 125,
			downloads: 203498,
			monthly_rank: 18,
			brand_id: "67",
			is_banned_in: "JP",
			preview_url: null,
			primary_color: null,
			created_at_unix: 1694512844,
			released_at_unix: 1692892336,
		},
		{
			id: 3126,
			name: "Imaizumin-chi wa Douyara Gal no Tamariba ni Natteru Rashii 4",
			slug: "imaizumin-chi-wa-douyara-gal-no-tamariba-ni-natteru-rashii-4",
			created_at: "2023-08-11T19:14:36.275Z",
			released_at: "2023-08-03T15:52:06.000Z",
			views: 7175962,
			interests: 160096,
			poster_url:
				"https://akidoo.top/images/posters/imaizumin-chi-wa-douyara-gal-no-tamariba-ni-natteru-rashii-4-pv1.png",
			cover_url:
				"https://akidoo.top/images/covers/imaizumin-chi-wa-douyara-gal-no-tamariba-ni-natteru-rashii-4-cv1.png",
			is_hard_subtitled: true,
			brand: "Bunnywalker",
			duration_in_ms: 0,
			is_censored: true,
			rating: 0,
			likes: 22634,
			dislikes: 130,
			downloads: 276751,
			monthly_rank: 19,
			brand_id: "10",
			is_banned_in: "JP",
			preview_url: null,
			primary_color: null,
			created_at_unix: 1691781276,
			released_at_unix: 1691077926,
		},
		{
			id: 3144,
			name: "Kunoichi Ryoujokuden Ajisai 2",
			slug: "kunoichi-ryoujokuden-ajisai-2",
			created_at: "2023-10-27T20:23:39.888Z",
			released_at: "2023-09-28T15:52:24.000Z",
			views: 892578,
			interests: 49675,
			poster_url:
				"https://akidoo.top/images/posters/kunoichi-ryoujokuden-ajisai-2-pv1.png",
			cover_url:
				"https://akidoo.top/images/covers/kunoichi-ryoujokuden-ajisai-2-cv1.png",
			is_hard_subtitled: true,
			brand: "Suzuki Mirano",
			duration_in_ms: 0,
			is_censored: true,
			rating: 0,
			likes: 4007,
			dislikes: 249,
			downloads: 30844,
			monthly_rank: 20,
			brand_id: "92",
			is_banned_in: "JP",
			preview_url: null,
			primary_color: null,
			created_at_unix: 1698438219,
			released_at_unix: 1695916344,
		},
		{
			id: 2856,
			name: "Imaizumin-chi wa Douyara Gal no Tamariba ni Natteru Rashii 1",
			slug: "imaizumin-chi-wa-douyara-gal-no-tamariba-ni-natteru-rashii-1",
			created_at: "2021-08-14T21:18:26.000Z",
			released_at: "2021-08-05T00:47:36.000Z",
			views: 15637384,
			interests: 443777,
			poster_url:
				"https://akidoo.top/images/posters/imaizumin-chi-wa-douyara-1-pv1.png",
			cover_url:
				"https://akidoo.top/images/covers/imaizumin-chi-wa-douyara-1-cv1.png",
			is_hard_subtitled: true,
			brand: "Bunnywalker",
			duration_in_ms: 0,
			is_censored: true,
			rating: 0,
			likes: 52669,
			dislikes: 170,
			downloads: 561974,
			monthly_rank: 21,
			brand_id: "10",
			is_banned_in: "JP",
			preview_url: null,
			primary_color: null,
			created_at_unix: 1628975906,
			released_at_unix: 1628124456,
		},
		{
			id: 3129,
			name: "Koumi-jima: Shuu 7 de Umeru Mesu-tachi 2",
			slug: "koumi-jima-shuu-7-de-umeru-mesu-tachi-2",
			created_at: "2023-08-29T09:49:10.965Z",
			released_at: "2023-05-16T15:52:09.000Z",
			views: 4890873,
			interests: 106841,
			poster_url:
				"https://akidoo.top/images/posters/koumi-jima-shuu-7-de-umeru-mesu-tachi-2-pv1.png",
			cover_url:
				"https://akidoo.top/images/covers/koumi-jima-shuu-7-de-umeru-mesu-tachi-2-cv1.png",
			is_hard_subtitled: true,
			brand: "Torudaya",
			duration_in_ms: 0,
			is_censored: true,
			rating: 0,
			likes: 14855,
			dislikes: 251,
			downloads: 159586,
			monthly_rank: 22,
			brand_id: "193",
			is_banned_in: "JP",
			preview_url: null,
			primary_color: null,
			created_at_unix: 1693302550,
			released_at_unix: 1684252329,
		},
		{
			id: 3140,
			name: "Toshoshitsu no Kanojo: Seiso na Kimi ga Ochiru made 6",
			slug: "toshoshitsu-no-kanojo-seiso-na-kimi-ga-ochiru-made-6",
			created_at: "2023-10-09T17:06:06.913Z",
			released_at: "2023-09-28T15:52:20.000Z",
			views: 2645854,
			interests: 101665,
			poster_url:
				"https://akidoo.top/images/posters/toshoshitsu-no-kanojo-seiso-na-kimi-ga-ochiru-made-6-pv1.png",
			cover_url:
				"https://akidoo.top/images/covers/toshoshitsu-no-kanojo-seiso-na-kimi-ga-ochiru-made-6-cv1.png",
			is_hard_subtitled: true,
			brand: "Pink Pineapple",
			duration_in_ms: 0,
			is_censored: true,
			rating: 0,
			likes: 7166,
			dislikes: 446,
			downloads: 82931,
			monthly_rank: 23,
			brand_id: "67",
			is_banned_in: "JP",
			preview_url: null,
			primary_color: null,
			created_at_unix: 1696871166,
			released_at_unix: 1695916340,
		},
		{
			id: 3139,
			name: "Tanetsuke Ojisan to Papakko JD Saimin Seikatsu 1",
			slug: "tanetsuke-ojisan-to-papakko-jd-saimin-seikatsu-1",
			created_at: "2023-10-09T16:43:00.306Z",
			released_at: "2023-09-28T15:52:19.000Z",
			views: 2367573,
			interests: 93067,
			poster_url:
				"https://akidoo.top/images/posters/tanetsuke-ojisan-to-papakko-jd-saimin-seikatsu-1-pv1.png",
			cover_url:
				"https://akidoo.top/images/covers/tanetsuke-ojisan-to-papakko-jd-saimin-seikatsu-1-cv1.png",
			is_hard_subtitled: true,
			brand: "Showten",
			duration_in_ms: 0,
			is_censored: true,
			rating: 0,
			likes: 9217,
			dislikes: 611,
			downloads: 82621,
			monthly_rank: 24,
			brand_id: "82",
			is_banned_in: "JP",
			preview_url: null,
			primary_color: null,
			created_at_unix: 1696869780,
			released_at_unix: 1695916339,
		},
	],
	time: "month",
	page_size: 24,
	page: 0,
	number_of_pages: 128,
	env: {
		vhtv_version: 1701441703913,
		premium_coin_cost: 4100,
		mobile_apps: {
			code_name: "",
			_build_number: 65,
			_semver: "3.7.1",
			_md5: "7782176b00d550cd2c28cd8ff3f8c3b2",
			_url: "https://static-assets.highwinds-cdn.com/apks/htv_app_v3.7.1-7782176b00d550cd2c28cd8ff3f8c3b2.apk",
		},
	},
	session_token: "",
	session_token_expire_time_unix: 0,
	user: null,
	user_setting: null,
	user_search_option: null,
	playlists: null,
};

export const videoData = {
    "player_base_url": "https://player.hanime.tv/?",
    "hentai_video": {
      "id": 3151,
      "is_visible": true,
      "name": "Majo wa Kekkyoku Sono Kyaku to 2",
      "slug": "majo-wa-kekkyoku-sono-kyaku-to-2",
      "created_at": "2023-11-15T20:48:18.494Z",
      "released_at": "2023-10-26T15:52:31.000Z",
      "description": "<p>During these days, her mother who is also a witch, noticed that her daughter's magical power was decreasing due to having too much sex with Leo...</p>\n\n<p>However, as she watched the situation between the two of them through a crystal ball, her body started to heat up...</p>",
      "views": 2293454,
      "interests": 77688,
      "poster_url": "https://akidoo.top/images/posters/majo-wa-kekkyoku-sono-kyaku-to-2-pv1.png",
      "cover_url": "https://akidoo.top/images/covers/majo-wa-kekkyoku-sono-kyaku-to-2-cv1.png",
      "is_hard_subtitled": true,
      "brand": "Pink Pineapple",
      "duration_in_ms": 0,
      "is_censored": true,
      "rating": 0.0,
      "likes": 9574,
      "dislikes": 130,
      "downloads": 79012,
      "monthly_rank": 1,
      "brand_id": "67",
      "is_banned_in": "JP",
      "preview_url": null,
      "primary_color": null,
      "created_at_unix": 1700081298,
      "released_at_unix": 1698335551,
      "hentai_tags": [
        {
          "id": 110,
          "text": "big boobs"
        },
        {
          "id": 104,
          "text": "dark skin"
        },
        {
          "id": 245,
          "text": "milf"
        },
        {
          "id": 40,
          "text": "anal"
        },
        {
          "id": 501,
          "text": "fantasy"
        },
        {
          "id": 526,
          "text": "x-ray"
        },
        {
          "id": 499,
          "text": "hd"
        },
        {
          "id": 20,
          "text": "creampie"
        },
        {
          "id": 523,
          "text": "censored"
        }
      ],
      "titles": [
        {
          "lang": "ja",
          "kind": "official",
          "title": "魔女は結局その客と... THE ANIMATION"
        },
        {
          "lang": "ko",
          "kind": "syn",
          "title": "마녀는 결국 그 손님과... THE ANIMATION"
        },
        {
          "lang": "x-jat",
          "kind": "main",
          "title": "Majo wa Kekkyoku Sono Kyaku to... The Animation"
        }
      ]
    },
    "hentai_tags": [
      {
        "id": 110,
        "text": "big boobs",
        "count": 1965,
        "description": "The greatest creation known to mankind.",
        "wide_image_url": "https://static-assets-44d.pages.dev/images/tags/big_boobs-horizontal.min.jpg",
        "tall_image_url": "https://static-assets-44d.pages.dev/images/tags/big_boobs-vertical.min.jpg"
      },
      {
        "id": 104,
        "text": "dark skin",
        "count": 185,
        "description": "Tanned beauties. 😍",
        "wide_image_url": "https://static-assets-44d.pages.dev/images/tags/dark_skin-horizontal.min.jpg",
        "tall_image_url": "https://static-assets-44d.pages.dev/images/tags/dark_skin-vertical.min.jpg"
      },
      {
        "id": 245,
        "text": "milf",
        "count": 265,
        "description": "Reverse loli.  Mom I'd Like to Fuck.",
        "wide_image_url": "https://static-assets-44d.pages.dev/images/tags/milf-horizontal.min.jpg",
        "tall_image_url": "https://static-assets-44d.pages.dev/images/tags/milf-vertical.min.jpg"
      },
      {
        "id": 40,
        "text": "anal",
        "count": 955,
        "description": "B-b-but I poop from there!",
        "wide_image_url": "https://static-assets-44d.pages.dev/images/tags/anal-horizontal.min.jpg",
        "tall_image_url": "https://static-assets-44d.pages.dev/images/tags/anal-vertical.min.jpg"
      },
      {
        "id": 501,
        "text": "fantasy",
        "count": 694,
        "description": "Fantasy world with mythical creatures, isekai or RPG porn.",
        "wide_image_url": "https://static-assets-44d.pages.dev/images/tags/fantasy-horizontal.min.jpg",
        "tall_image_url": "https://static-assets-44d.pages.dev/images/tags/fantasy-vertical.min.jpg"
      },
      {
        "id": 526,
        "text": "x-ray",
        "count": 302,
        "description": "Learning about female body internals during sex.",
        "wide_image_url": "https://static-assets-44d.pages.dev/images/tags/x-ray-horizontal.min.jpg",
        "tall_image_url": "https://static-assets-44d.pages.dev/images/tags/x-ray-vertical.min.jpg"
      },
      {
        "id": 499,
        "text": "hd",
        "count": 1927,
        "description": "Blu-ray quality videos in high res so you can see top-notch censors.",
        "wide_image_url": "https://static-assets-44d.pages.dev/images/tags/hd-horizontal.min.jpg",
        "tall_image_url": "https://static-assets-44d.pages.dev/images/tags/hd-vertical.min.jpg"
      },
      {
        "id": 20,
        "text": "creampie",
        "count": 1899,
        "description": "Reverse birth control when a guy cums inside. Whoops.",
        "wide_image_url": "https://static-assets-44d.pages.dev/images/tags/creampie-horizontal.min.jpg",
        "tall_image_url": "https://static-assets-44d.pages.dev/images/tags/creampie-vertical.min.jpg"
      },
      {
        "id": 523,
        "text": "censored",
        "count": 1824,
        "description": "The parts you came to see are all pixelated, cucked by Japan.",
        "wide_image_url": "https://static-assets-44d.pages.dev/images/tags/censored-horizontal.min.jpg",
        "tall_image_url": "https://static-assets-44d.pages.dev/images/tags/censored-vertical.min.jpg"
      }
    ],
    "hentai_franchise": {
      "id": 1209,
      "name": "majo wa kekkyoku",
      "slug": "majo-wa-kekkyoku",
      "title": "Majo wa Kekkyoku"
    },
    "hentai_franchise_hentai_videos": [
      {
        "id": 3071,
        "name": "Majo wa Kekkyoku Sono Kyaku to 1",
        "slug": "majo-wa-kekkyoku-sono-kyaku-to-1",
        "created_at": "2023-03-02T17:57:59.000Z",
        "released_at": "2023-02-23T15:51:11.000Z",
        "views": 5340956,
        "interests": 170123,
        "poster_url": "https://akidoo.top/images/posters/majo-wa-kekkyoku-sono-kyaku-to-1-pv1.png",
        "cover_url": "https://akidoo.top/images/covers/majo-wa-kekkyoku-sono-kyaku-to-1-cv1.png",
        "is_hard_subtitled": true,
        "brand": "Pink Pineapple",
        "duration_in_ms": 0,
        "is_censored": true,
        "rating": 0.0,
        "likes": 11715,
        "dislikes": 81,
        "downloads": 213408,
        "monthly_rank": 17,
        "brand_id": "67",
        "is_banned_in": "JP",
        "preview_url": null,
        "primary_color": null,
        "created_at_unix": 1677779879,
        "released_at_unix": 1677167471
      },
      {
        "id": 3151,
        "name": "Majo wa Kekkyoku Sono Kyaku to 2",
        "slug": "majo-wa-kekkyoku-sono-kyaku-to-2",
        "created_at": "2023-11-15T20:48:18.494Z",
        "released_at": "2023-10-26T15:52:31.000Z",
        "views": 2293454,
        "interests": 77688,
        "poster_url": "https://akidoo.top/images/posters/majo-wa-kekkyoku-sono-kyaku-to-2-pv1.png",
        "cover_url": "https://akidoo.top/images/covers/majo-wa-kekkyoku-sono-kyaku-to-2-cv1.png",
        "is_hard_subtitled": true,
        "brand": "Pink Pineapple",
        "duration_in_ms": 0,
        "is_censored": true,
        "rating": 0.0,
        "likes": 9574,
        "dislikes": 130,
        "downloads": 79012,
        "monthly_rank": 1,
        "brand_id": "67",
        "is_banned_in": "JP",
        "preview_url": null,
        "primary_color": null,
        "created_at_unix": 1700081298,
        "released_at_unix": 1698335551
      }
    ],
    "hentai_video_storyboards": [
      {
        "id": 14985,
        "num_total_storyboards": 1,
        "sequence": 0,
        "url": "https://akidoo.top/images/storyboards/majo-wa-kekkyoku-sono-kyaku-to-2-720p-h1x.jpg",
        "frame_width": 160,
        "frame_height": 90,
        "num_total_frames": 180,
        "num_horizontal_frames": 5,
        "num_vertical_frames": 36
      }
    ],
    "brand": {
      "id": 67,
      "title": "Pink Pineapple",
      "slug": "pink-pineapple",
      "website_url": null,
      "logo_url": null,
      "email": null,
      "count": 521
    },
    "watch_later_playlist_hentai_videos": null,
    "like_dislike_playlist_hentai_videos": null,
    "playlist_hentai_videos": null,
    "similar_playlists_data": null,
    "next_hentai_video": {
      "id": 3152,
      "name": "Korashime 2: Kyouikuteki Depaga Shidou 4",
      "slug": "korashime-2-kyouikuteki-depaga-shidou-4",
      "created_at": "2023-11-21T22:26:55.735Z",
      "released_at": "2023-10-26T15:52:32.000Z",
      "views": 752850,
      "interests": 46626,
      "poster_url": "https://akidoo.top/images/posters/korashime-2-kyouikuteki-depaga-shidou-4-pv1.png",
      "cover_url": "https://akidoo.top/images/covers/korashime-2-kyouikuteki-depaga-shidou-4-cv1.png",
      "is_hard_subtitled": true,
      "brand": "PoRO",
      "duration_in_ms": 0,
      "is_censored": true,
      "rating": 0.0,
      "likes": 3424,
      "dislikes": 92,
      "downloads": 25074,
      "monthly_rank": 14,
      "brand_id": "70",
      "is_banned_in": "JP",
      "preview_url": null,
      "primary_color": null,
      "created_at_unix": 1700605615,
      "released_at_unix": 1698335552
    },
    "next_random_hentai_video": {
      "id": 3093,
      "name": "Joshi Luck! 3",
      "slug": "joshi-luck-3",
      "created_at": "2023-05-11T00:19:25.229Z",
      "released_at": "2023-05-04T15:51:33.000Z",
      "views": 4933120,
      "interests": 138205,
      "poster_url": "https://akidoo.top/images/posters/joshi-luck-3-pv2.png",
      "cover_url": "https://akidoo.top/images/covers/joshi-luck-3-cv1.png",
      "is_hard_subtitled": true,
      "brand": "Bunnywalker",
      "duration_in_ms": 0,
      "is_censored": true,
      "rating": 0.0,
      "likes": 18442,
      "dislikes": 110,
      "downloads": 175239,
      "monthly_rank": 81,
      "brand_id": "10",
      "is_banned_in": "JP",
      "preview_url": null,
      "primary_color": null,
      "created_at_unix": 1683764365,
      "released_at_unix": 1683215493
    },
    "videos_manifest": {
      "servers": [
        {
          "id": 9,
          "name": "Shiva",
          "slug": "cf-hls",
          "na_rating": 3,
          "eu_rating": 3,
          "asia_rating": 3,
          "sequence": 70,
          "is_permanent": true,
          "streams": [
            {
              "id": 65508,
              "server_id": 9,
              "slug": "cf-hls-3151-majo-wa-kekkyoku-sono-kyaku-to-2-h1x-1080",
              "kind": "premium_alert",
              "extension": "m3u8",
              "mime_type": "application/x-mpegURL",
              "width": 1920,
              "height": "1080",
              "duration_in_ms": 1564000,
              "filesize_mbs": 543,
              "filename": "majo-wa-kekkyoku-sono-kyaku-to-2-1080p-h1x.mp4-h1x.m3u8",
              "url": "",
              "is_guest_allowed": false,
              "is_member_allowed": false,
              "is_premium_allowed": true,
              "is_downloadable": false,
              "compatibility": "all",
              "hv_id": 3151,
              "server_sequence": 70,
              "video_stream_group_id": "majo-wa-kekkyoku-sono-kyaku-to-2-h1x",
              "extra2": null
            },
            {
              "id": 65506,
              "server_id": 9,
              "slug": "cf-hls-3151-majo-wa-kekkyoku-sono-kyaku-to-2-h1x-720",
              "kind": "hls",
              "extension": "m3u8",
              "mime_type": "application/x-mpegURL",
              "width": 1280,
              "height": "720",
              "duration_in_ms": 1564000,
              "filesize_mbs": 302,
              "filename": "majo-wa-kekkyoku-sono-kyaku-to-2-720p-h1x.mp4-h1x.m3u8",
              "url": "https://m3u8s.highwinds-cdn.com/api/v9/m3u8s/gjtvcvAxd8gkyc5jh9phnq5hf2Zp06c9lAw1vp715k8pbnbAfwltA.m3u8",
              "is_guest_allowed": true,
              "is_member_allowed": true,
              "is_premium_allowed": true,
              "is_downloadable": false,
              "compatibility": "all",
              "hv_id": 3151,
              "server_sequence": 70,
              "video_stream_group_id": "majo-wa-kekkyoku-sono-kyaku-to-2-h1x",
              "extra2": null
            },
            {
              "id": 65504,
              "server_id": 9,
              "slug": "cf-hls-3151-majo-wa-kekkyoku-sono-kyaku-to-2-h1x-480",
              "kind": "hls",
              "extension": "m3u8",
              "mime_type": "application/x-mpegURL",
              "width": 854,
              "height": "480",
              "duration_in_ms": 1564000,
              "filesize_mbs": 113,
              "filename": "majo-wa-kekkyoku-sono-kyaku-to-2-480p-h1x.mp4-h1x.m3u8",
              "url": "https://m3u8s.highwinds-cdn.com/api/v9/m3u8s/y7clnwAf63k7d73nd84fr0l0jmZwwrk0jA9s1bdq20158x57nhmz3.m3u8",
              "is_guest_allowed": true,
              "is_member_allowed": true,
              "is_premium_allowed": true,
              "is_downloadable": false,
              "compatibility": "all",
              "hv_id": 3151,
              "server_sequence": 70,
              "video_stream_group_id": "majo-wa-kekkyoku-sono-kyaku-to-2-h1x",
              "extra2": null
            },
            {
              "id": 65502,
              "server_id": 9,
              "slug": "cf-hls-3151-majo-wa-kekkyoku-sono-kyaku-to-2-h1x-360",
              "kind": "hls",
              "extension": "m3u8",
              "mime_type": "application/x-mpegURL",
              "width": 640,
              "height": "360",
              "duration_in_ms": 1564000,
              "filesize_mbs": 83,
              "filename": "majo-wa-kekkyoku-sono-kyaku-to-2-360p-h1x.mp4-h1x.m3u8",
              "url": "https://m3u8s.highwinds-cdn.com/api/v9/m3u8s/fjr9jw9tndvAl6w5qry86jp2gqZx0y378Ag5hyl0z0zqrl0pqndry.m3u8",
              "is_guest_allowed": true,
              "is_member_allowed": true,
              "is_premium_allowed": true,
              "is_downloadable": false,
              "compatibility": "all",
              "hv_id": 3151,
              "server_sequence": 70,
              "video_stream_group_id": "majo-wa-kekkyoku-sono-kyaku-to-2-h1x",
              "extra2": null
            }
          ]
        }
      ]
    },
    "user_license": null,
    "bs": {
      "ntv_1": {
        "desktop": {
          "id": 16,
          "ad_id": "mindgeek_video_ntv_1_desktop",
          "ad_type": "ifr",
          "placement": "ntv_1",
          "image_url": null,
          "iframe_url": "https://ads.trafficjunky.net/ads?zone_id=1775851&site_id=16981&format=HTML&cache=1519396666",
          "click_url": null,
          "width": 300,
          "height": 250,
          "page": "video",
          "form_factor": "desktop",
          "video_url": null,
          "impressions": 0,
          "clicks": 0,
          "seconds": 8,
          "placement_x": null
        }
      },
      "ntv_2": {
        "desktop": {
          "id": 17,
          "ad_id": "mindgeek_video_ntv_2_desktop",
          "ad_type": "ifr",
          "placement": "ntv_2",
          "image_url": null,
          "iframe_url": "https://ads.trafficjunky.net/ads?zone_id=1775861&site_id=16981&format=HTML&cache=1519396679",
          "click_url": null,
          "width": 300,
          "height": 250,
          "page": "video",
          "form_factor": "desktop",
          "video_url": null,
          "impressions": 0,
          "clicks": 0,
          "seconds": 8,
          "placement_x": null
        }
      },
      "footer_0": {
        "mobile": {
          "id": 18,
          "ad_id": "mindgeek_video_footer_0_mobile",
          "ad_type": "ifr",
          "placement": "footer_0",
          "image_url": null,
          "iframe_url": "https://a.adtng.com/get/10000715?time=1639179663045",
          "click_url": null,
          "width": 300,
          "height": 250,
          "page": "video",
          "form_factor": "mobile",
          "video_url": null,
          "impressions": 0,
          "clicks": 0,
          "seconds": 8,
          "placement_x": null
        },
        "desktop": {
          "id": 19,
          "ad_id": "mindgeek_video_footer_0_desktop",
          "ad_type": "ifr",
          "placement": "footer_0",
          "image_url": null,
          "iframe_url": "https://a.adtng.com/get/10000770?time=1604959679983",
          "click_url": "https://a.adtng.com/get/10002115",
          "width": 950,
          "height": 250,
          "page": "video",
          "form_factor": "desktop",
          "video_url": null,
          "impressions": 0,
          "clicks": 0,
          "seconds": 8,
          "placement_x": null
        }
      },
      "native_1": {
        "mobile": {
          "id": 48,
          "ad_id": "mindgeek_video_native_1_mobile_33",
          "ad_type": "native",
          "placement": "native_1",
          "image_url": "https://static-assets-44d.pages.dev/images/partners/KOK_160x160_kyoko1.gif",
          "iframe_url": null,
          "click_url": "https://track.aftrk3.com/54e767bd-79fe-4894-82d1-a9245a60d690?game=kingofkinks&banner=kyoko1",
          "width": 160,
          "height": 160,
          "page": "video",
          "form_factor": "mobile",
          "video_url": null,
          "impressions": 0,
          "clicks": 0,
          "seconds": 8,
          "placement_x": "Hentai game – King of Kinks,Start the best kinky hentai adventures now, it’s free to play!"
        }
      },
      "native_0": {
        "mobile": {
          "id": 29,
          "ad_id": "mindgeek_video_native_0_mobile",
          "ad_type": "native",
          "placement": "native_0",
          "image_url": "https://static-assets-44d.pages.dev/images/partners/nutaku-logo.png",
          "iframe_url": null,
          "click_url": "https://track.afcpatrk.com/54e767bd-79fe-4894-82d1-a9245a60d690?game=nutaku&banner=nutakuicon",
          "width": 40,
          "height": 40,
          "page": "video",
          "form_factor": "mobile",
          "video_url": null,
          "impressions": 0,
          "clicks": 0,
          "seconds": 8,
          "placement_x": "Nutaku Gaming Portal,Join the best adult gaming site today for free!"
        }
      },
      "ntv_0": {
        "desktop": {
          "id": 15,
          "ad_id": "mindgeek_video_ntv_0_desktop",
          "ad_type": "ifr",
          "placement": "ntv_0",
          "image_url": null,
          "iframe_url": "https://a.adtng.com/get/10000694?time=1639179728367",
          "click_url": "https://a.adtng.com/get/10000694?time=1604959533080",
          "width": 300,
          "height": 250,
          "page": "video",
          "form_factor": "desktop",
          "video_url": null,
          "impressions": 0,
          "clicks": 0,
          "seconds": 8,
          "placement_x": null
        }
      }
    },
    "ap": 0.33,
    "pre": "https%3A%2F%2Fa.adtng.com%2Fget%2F10002722%3Ftime%3D1639180065082",
    "env": {
      "vhtv_version": 1701441703913,
      "premium_coin_cost": 4100,
      "mobile_apps": {
        "code_name": "",
        "_build_number": 65,
        "_semver": "3.7.1",
        "_md5": "7782176b00d550cd2c28cd8ff3f8c3b2",
        "_url": "https://static-assets.highwinds-cdn.com/apks/htv_app_v3.7.1-7782176b00d550cd2c28cd8ff3f8c3b2.apk"
      }
    },
    "session_token": "",
    "session_token_expire_time_unix": 0,
    "user": null,
    "user_setting": null,
    "user_search_option": null,
    "playlists": null
  }